### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by JarlPenguin** [JarlPenguin/releases#1]
- [x] Make Telegram variables optional
- [x] Add build type to config.sh (userdebug, user, eng) - done, https://github.com/JarlPenguin/releases/commit/3dd2f24b4b036ded456083255c681d47f6c368f1
- [x] Rebase twrp-master & and all TWRP branches to master
